@echo Off
echo Futtatas..
SET sikeres=0
SET ossz=0
java protoApp.ProtoApp < tests/test_in/test01 > test01_out & java protoApp.ProtoApp < tests/test_in/test02 > test02_out & java protoApp.ProtoApp < tests/test_in/test03 > test03_out & java protoApp.ProtoApp < tests/test_in/test04 > test04_out & java protoApp.ProtoApp < tests/test_in/test05 > test05_out & java protoApp.ProtoApp < tests/test_in/test06 > test06_out & java protoApp.ProtoApp < tests/test_in/test07 > test07_out & java protoApp.ProtoApp < tests/test_in/test08 > test08_out & java protoApp.ProtoApp < tests/test_in/test09 > test09_out & java protoApp.ProtoApp < tests/test_in/test10 > test10_out & java protoApp.ProtoApp < tests/test_in/test11 > test11_out & java protoApp.ProtoApp < tests/test_in/test12 > test12_out & java protoApp.ProtoApp < tests/test_in/test13 > test13_out & java protoApp.ProtoApp < tests/test_in/test14 > test14_out & java protoApp.ProtoApp < tests/test_in/test15 > test15_out & java protoApp.ProtoApp < tests/test_in/test16 > test16_out & java protoApp.ProtoApp < tests/test_in/test17 > test17_out & java protoApp.ProtoApp < tests/test_in/test18 > test18_out & java protoApp.ProtoApp < tests/test_in/test19 > test19_out & java protoApp.ProtoApp < tests/test_in/test20 > test20_out & java protoApp.ProtoApp < tests/test_in/test21 > test21_out
echo Futtatas kesz, osszehasonlitas..
(SET /A ossz=ossz+1 && fc test01_out tests/test_expected/test01_expected && SET /A sikeres=sikeres+1) & (SET /A ossz=ossz+1 && fc test02_out tests/test_expected/test02_expected && SET /A sikeres=sikeres+1) & (SET /A ossz=ossz+1 && fc test03_out tests/test_expected/test03_expected && SET /A sikeres=sikeres+1) & (SET /A ossz=ossz+1 && fc test04_out tests/test_expected/test04_expected && SET /A sikeres=sikeres+1) & (SET /A ossz=ossz+1 && fc test05_out tests/test_expected/test05_expected && SET /A sikeres=sikeres+1) & (SET /A ossz=ossz+1 && fc test06_out tests/test_expected/test06_expected && SET /A sikeres=sikeres+1) & (SET /A ossz=ossz+1 && fc test07_out tests/test_expected/test07_expected && SET /A sikeres=sikeres+1) & (SET /A ossz=ossz+1 && fc test08_out tests/test_expected/test08_expected && SET /A sikeres=sikeres+1) & (SET /A ossz=ossz+1 && fc test09_out tests/test_expected/test09_expected && SET /A sikeres=sikeres+1) & (SET /A ossz=ossz+1 && fc test10_out tests/test_expected/test10_expected && SET /A sikeres=sikeres+1) & (SET /A ossz=ossz+1 && fc test11_out tests/test_expected/test11_expected && SET /A sikeres=sikeres+1) & (SET /A ossz=ossz+1 && fc test12_out tests/test_expected/test12_expected && SET /A sikeres=sikeres+1) & (SET /A ossz=ossz+1 && fc test13_out tests/test_expected/test13_expected && SET /A sikeres=sikeres+1) & (SET /A ossz=ossz+1 && fc test14_out tests/test_expected/test14_expected && SET /A sikeres=sikeres+1) & (SET /A ossz=ossz+1 && fc test15_out tests/test_expected/test15_expected && SET /A sikeres=sikeres+1) & (SET /A ossz=ossz+1 && fc test16_out tests/test_expected/test16_expected && SET /A sikeres=sikeres+1) & (SET /A ossz=ossz+1 && fc test17_out tests/test_expected/test17_expected && SET /A sikeres=sikeres+1) & (SET /A ossz=ossz+1 && fc test18_out tests/test_expected/test18_expected && SET /A sikeres=sikeres+1) & (SET /A ossz=ossz+1 && fc test19_out tests/test_expected/test19_expected && SET /A sikeres=sikeres+1) & (SET /A ossz=ossz+1 && fc test20_out tests/test_expected/test20_expected && SET /A sikeres=sikeres+1) & (SET /A ossz=ossz+1 && fc test21_out tests/test_expected/test21_expected && SET /A sikeres=sikeres+1)
echo Osszehasonlitas kesz.
echo %ossz% tesztbol %sikeres% sikeresen lefutott
@echo On
pause
